#!/sbin/runscript
# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
  need net
  use logger dns zookeeper docker
}

start() {
  ebegin "Starting Mesos Agent"
  start-stop-daemon --background --make-pidfile \
    --pidfile /var/run/mesos-agent.pid \
    --stdout /var/log/mesos-agent.log \
    --stderr /var/log/mesos-agent.log \
    --start --exec /usr/local/bin/supervisor -- \
        --pidfile /var/run/mesos-agent-via-supervisor.pid \
        --restart-on-crash \
        --restart-on-error \
        --delay-limit=10 \
        -- /usr/sbin/mesos-init-wrapper agent
  eend $?
}

stop() {
  ebegin "Stopping Mesos Agent"
  start-stop-daemon \
    --pidfile /var/run/mesos-agent.pid \
    --stop --exec /usr/local/bin/supervisor
  eend $?
}
